title: <p align="center"> Vinoth Somu </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vinoth-somu/">LinkedIn</a> |
  <a href="https://github.com/vinothsomu">GitHub</a>
 
  <br>  
  I'm working on Java, Cloud Service, Data engineering related problems.
  Also handing the Data migration for the products.
  Working in HCLTech on networking domain for 10 years.
  <br>
  </p>



theme: jekyll-theme-minimal
